package compiler.Lexer;

public enum TokenType {
    BASE_TYPE,BOOLEAN,COMMENT,EOL,EOF,IDENTIFIER,KEYWORD, INTEGER, FLOAT,STRINGS,OPERATOR,RECORD_NAME,VOID_TYPE,ARRAY_TYPE,MAIN, ATTRIBUTE,FUNC_NAME
}
