/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package compiler;

import compiler.Lexer.FileToReader;
import compiler.Lexer.Lexer;
import compiler.Parser.Grammar.*;
import compiler.Parser.Parser;
import compiler.Semantic.Semantic;
import compiler.CodeGeneration.CodeGenerator;

import java.io.Reader;

public class Compiler {
    public static void main(String[] args) throws Exception {
       if (args.length == 2 && args[0].equals("-lexer")) {

           String filepath = args[1];
           Reader readerFile = FileToReader.getReaderFromFile(filepath);
           Lexer lexer = new Lexer(readerFile);

           while (lexer.hasNextSymbol()) {
               System.out.println(lexer.getNextSymbol());
           }
       }

       else if (args.length == 2 && args[0].equals("-parser")){
            String filepath = args[1];
            Reader readerFile = FileToReader.getReaderFromFile(filepath);
            Lexer lexer = new Lexer(readerFile);
            Parser parser = new Parser(lexer);
            Ast myAst = parser.getAST();
            System.out.println(myAst);

       }
       else if (args.length == 2 && args[0].equals("-semantic")) {
           System.out.println("SEMANTIC ANALYSIS");
           String filepath = args[1];
           Reader readerFile = FileToReader.getReaderFromFile(filepath);
           Lexer lexer = new Lexer(readerFile);
           Parser parser = new Parser(lexer);
           Ast myAst = parser.getAST();
           Semantic semantic = new Semantic(myAst);
           semantic.startAnalysis();

       }

       else if (args.length == 2 && args[0].equals("-semantic")) {
           String sourceFilePath = args[1];
           String targetFilePath;
           Reader readerFile = FileToReader.getReaderFromFile(sourceFilePath);
           Lexer lexer = new Lexer(readerFile);
           Parser parser = new Parser(lexer);
           Ast myAst = parser.getAST();
           Semantic semantic = new Semantic(myAst);
           semantic.startAnalysis();
       }

       else {
           // soureFile -o targetfile

           String sourceFilePath = args[0];
           String targetFilePath;
           if (args.length == 3) {
               targetFilePath = args[2];
           }
           else{
               targetFilePath = "CompiledCode";
           }
           Reader readerFile = FileToReader.getReaderFromFile(sourceFilePath);
           Lexer lexer = new Lexer(readerFile);
           Parser parser = new Parser(lexer);
           Ast myAst = parser.getAST();
           Semantic semantic = new Semantic(myAst);
           semantic.startAnalysis();
           CodeGenerator cg = new CodeGenerator(targetFilePath,myAst);
           cg.generateFileClass();
       }
       System.exit(0);
    }
}
